APPLICATION = weather-station

BOARD ?= nucleo-f401re
RIOTBASE ?= ${HOME}/Tutorials/RIOT

FEATURES_REQUIRED = periph_gpio
FEATURES_REQUIRED = periph_gpio_irq
USEMODULE += xtimer
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

include $(RIOTBASE)/Makefile.include
